apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: support-ticket-labelling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support-ticket-labelling
    spec:
      containers:
      - name: support-ticket-labelling
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/support-labelling-webhooks:v0.6
        ports:
        - containerPort: 4567
          name: http
        env:
        - name: GITHUB_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-access-token
              key: github-access-token
