apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: support-ticket-labelling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support-ticket-labelling
    spec:
      containers:
      - name: support-ticket-labelling
        image: ministryofjustice/cloud-platform-support-labelling-webhook:0.7
        ports:
        - containerPort: 4567
          name: http
        env:
        - name: GITHUB_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-access-token
              key: github-access-token
