apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: support-ticket-labelling-ing
  namespace: support-labelling-webhook
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: support-ticket-labelling.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: support-ticket-labelling-svc
          servicePort: 80
  tls:
  - hosts:
    - support-ticket-labelling.apps.live-1.cloud-platform.service.justice.gov.uk

