apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: support-ticket-labelling-ing
  namespace: support-labelling-webhook-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: support-ticket-labelling.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: support-ticket-labelling-svc
          servicePort: 80